CREATE TABLE IF NOT EXIST cargo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL
);

CREATE TABLE IF NOT EXIST trabalhador (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cargo_id INTEGER,
    FOREIGN KEY (cargo_id) REFERENCES cargo(id)
);

CREATE TABLE IF NOT EXIST horario(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hora_inicio TEXT NOT NULL,
    hora_fim TEXT NOT NULL
);

CREATE TABLE IF NOT EXIST dia_semana(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL
);

